export const LANDING_IMAGES = {
  heroBg: "/images/landing/hero-bg.jpg",
  heroTestDrive: "/images/landing/hero-test-drive.jpg",
  logoKgmWhite: "/images/landing/logo-kgm-white.png",
  logoChampionWhite: "/images/landing/logo-champion-white.png",
  aboutExterior: "/images/landing/about-exterior.jpg",
  bigExterior: "/images/landing/big-exterior.png",
  aboutInterior: "/images/landing/about-interior.jpg",
  aboutMotion: "/images/landing/about-motion.jpg",
  prize1: "/images/landing/prize-1.jpg",
  prize2: "/images/landing/prize-2.jpg",
  prize3: "/images/landing/prize-3.jpg",
  howToParticipate: "/images/landing/how-to-participate.png",
  qrDemo: "/images/landing/qr-demo.png",
  registerBenefit1: "/images/landing/register-benefit-1.svg",
  registerBenefit2: "/images/landing/register-benefit-2.svg",
  registerBenefit3: "/images/landing/register-benefit-3.svg",
  registerBenefit4: "/images/landing/register-benefit-4.svg",
} as const;
